[package]
name = "ctaes"
version = "0.1.0"
authors = ["Blockstream <support@blockstream.com>"]
links = "ctaes"
edition = "2015"

[dependencies]
thiserror = "1.0.30"
zeroize = "1"

[dev-dependencies]
hex-conservative = "0.2.1"

[build-dependencies]
cc = "^1.0"
